import Head from "next/head";
import { useRouter } from "next/router";
import Image from "next/image";
import WebBrowserSticky from "../components/WebBrowserSticky";
import MainPageServices from "../components/MainPageServices";
import PlayIcon from "../public/images/PlayIcon.svg";
import Link from "next/link";
import OurWorkCard from "../components/OurWorkCard";
import PlusIcon from "../public/images/plus.svg";
import { Swiper, SwiperSlide } from "swiper/react";
import { EffectCoverflow } from "swiper";
import "swiper/css";
import "swiper/css/effect-coverflow";

export default function Home({ posts, works, employeer, blog, comment }) {
  const router = useRouter();
  return (
    <div>
      <Head>
        <title>GlobalSoft</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className="main-page ">
          <div className="main-page-container container">
            <div className="main-page-top">
              <div className="main-page-header">
                <h1>KREATİV, UNİKAL VƏ İNNOVATİV</h1>
              </div>
              <div className="main-page-text-and-button">
                <p>Debitis esse quisquam necessitatibus deleniti iusto repellendus. In eum aperiam nam enim recusandae ut dignissimos. </p>
                <button onClick={() => router.push("/about")}>
                  Haqqımızda
                  <div className="play-icon">
                    <Image src={PlayIcon} alt="PlayIcon" />
                  </div>
                </button>
              </div>
            </div>
            <WebBrowserSticky />
            <section className="main-page-services">
              <h1>Xidmətlərimiz</h1>
              <MainPageServices posts={posts} />
            </section>
          </div>
        </section>
        <section className="our-works">
          <div className="container">
            <div className="our-works-text">
              <h1>İşlərimiz</h1>
              <div className="paragraph-link">
                <p>Quas distinctio cumque. Adipisci deserunt minima laudantium consequatur eum ea id accusantium id. Blanditiis </p>
                <Link href="/ourWorks">Hamısına bax</Link>
              </div>
            </div>
            <div className="our-works-cards">
              {works.slice(0, 4).map((card, key) => (
                <OurWorkCard card={card} key={key} />
              ))}
            </div>
          </div>
        </section>
        <section className="our-team">
          <div className="our-team-context container">
            <div className="our-team-text">
              <h3>Bizim komanda</h3>
              <p>
                Quas distinctio cumque. Adipisci deserunt minima laudantium consequatur eum ea id accusantium id. Blanditiis id molestiae ratione est
                nihil dicta sed. Voluptatem deleniti sunt expedita et. Et laborum eum placeat eos maxime ea.
              </p>
            </div>
            {employeer.map((card, key) => (
              <div className="card" key={key}>
                <div className="card-image">
                  <div className="img" style={{ backgroundImage: `url(${card.img.src})` }}></div>
                </div>
                <div className="card-info">
                  <h5>{card.name}</h5>
                  <span>{card.job}</span>
                </div>
              </div>
            ))}
            <div className="card plus">
              <div className="card-image">
                <Image src={PlusIcon} alt="Plus" />
              </div>
              <div className="card-info">
                <h5>Komandamıza qoşulun</h5>
              </div>
            </div>
          </div>
        </section>
        <div className="blog-comments">
          <section>
            <div className="blog-context container">
              <div className="blog-text">
                <h3>Bloq</h3>
                <div className="paragraph-link">
                  <p>Quas distinctio cumque. Adipisci deserunt minima laudantium consequatur eum ea id accusantium id. Blanditiis </p>
                  <Link href="/blog">Hamısına bax</Link>
                </div>
                <Swiper slidesPerView={4.5} spaceBetween={80} grabCursor={true} className="mySwiper">
                  {blog.map((carousel) => (
                    <SwiperSlide key={carousel.id}>
                      <Link href={"#"}>
                        <div className="carousel">
                          <h5>{carousel.name}</h5>
                          <div className="carousel-image">
                            <Image src={carousel.img} alt={carousel.name} />
                          </div>
                        </div>
                      </Link>
                    </SwiperSlide>
                  ))}
                </Swiper>
              </div>
            </div>
          </section>

          <section className="comments">
            <div className="comments-context container">
              <div className="comments-text">
                <h3>Müştəriləmizin rəyləri</h3>
                <p>Quas distinctio cumque. Adipisci deserunt minima laudantium consequatur eum ea id accusantium id. Blanditiis </p>
              </div>
              <Swiper
                effect={"coverflow"}
                grabCursor={true}
                centeredSlides={true}
                slidesPerView={"2"}
                coverflowEffect={{
                  rotate: 0,
                  stretch: 0,
                  depth: 600,
                  modifier: 1,
                  slideShadows: true,
                }}
                loop={true}
                modules={[EffectCoverflow]}
                className="commentsSwiper"
              >
                {comment.map((carousel) => (
                  <SwiperSlide key={carousel.id}>
                    <div className="carousel">
                      <p>{carousel.p}</p>
                      <div className="person-info">
                        <div className="person-photo">
                          <Image src={carousel.img} alt={carousel.name} />
                        </div>
                        <div className="person-name">
                          <h5>{carousel.name}</h5>
                          <p>{carousel.job}</p>
                        </div>
                      </div>
                    </div>
                  </SwiperSlide>
                ))}
              </Swiper>
            </div>
          </section>
        </div>
      </main>
    </div>
  );
}

export async function getServerSideProps() {
  const res = await fetch("http://localhost:3000/api/servicesApi/");
  const posts = await res.json();

  const workRes = await fetch("http://localhost:3000/api/workApi/");
  const works = await workRes.json();

  const employeerRes = await fetch("http://localhost:3000/api/personApi/");
  const employeer = await employeerRes.json();

  const blogRes = await fetch("http://localhost:3000/api/blogApi/");
  const blog = await blogRes.json();

  const commentRes = await fetch("http://localhost:3000/api/commentApi/");
  const comment = await commentRes.json();
  return {
    props: {
      posts,
      works,
      employeer,
      blog,
      comment,
    },
  };
}
